version: "3.8"
services:
  web:
   image: nk18989/staycation-backend
   build: .
   volumes:
      - /usr/src/app/node_modules
   ports:
   - "3000:3000"
   depends_on:
   - mongo
   container_name: StaycationBackend
  mongo:
   image: mongo
   container_name: StaycationDB
   volumes: 
      - ./mongo-data:/data/db
   ports:
   - "27017:27017"
